### ISSUE TITLE
Program type already present

### ISSUE THREAD

**Issue by MuhammedAlmaz** [adjust/react_native_sdk#161]
I checked all dependency on my packages but there is not any package which using react-native-adjust. I tried force only one time implement the dependency with this code block but it doesn't work already.

Force implementation code;
```.gradle
    configurations.all {
        resolutionStrategy {
            force  group: 'com.adjust.sdk', name: 'adjust-android', version: '4.29.1'
        }
    }
```

```error
AGPBI: {"kind":"error","text":"Program type already present: com.adjust.sdk.ActivityHandler$10","sources":[{}],"tool":"D8"}
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: com.adjust.sdk.ActivityHandler$10
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
```

**Comment by uerceg** [comment]
Hi @MuhammedAlmaz,

In current state of things, our React Native SDK contains our native Android SDK added as a [JAR dependency](https://github.com/adjust/react_native_sdk/tree/master/android/libs). So there is no need to have any other reference to it in your Gradle file. Are you still facing the same issue if you remove all native Adjust Android SDK references from Gradle file?

**Comment by MuhammedAlmaz** [comment]
Hi @uerceg ,

I checked all gradle files there is not any adjust sdk. I removed all but i guess this error again. Idk why. I clear gradle files, caches etc.

**Comment by Aditi3** [comment]
I hope this issue is resolved. I'll go ahead and close it, but feel free to comment or reopen if you encounter any issues with our latest releases.
